### ISSUE TITLE
Any thought to letting different validators call different runnables?

### ISSUE THREAD

**Issue by aychedee** [jeffh/sniffer#19]
I would quite like to extend sniffer so that I can have it run nose when it finds a modified '.py' file and run mocha when it finds a modified '.js' file. Would you have any interest in a patch like this? 

As long as I can keep it simple and backwards compatible of course...

**Comment by jeffh** [comment]
Hey @aychedee, this looks good to me! Do you think supporting multiple file_validators per runnable is reasonable? I don't really know but that's just something to consider.

Just add some example to the README and submit the PR and I'll merge it. And thanks for writing tests (something I've been slacking too much on this project).

**Comment by jeffh** [comment]
Thanks for the PR @aychedee! I merged #21 to master and it should be up on pypi too.
