### ISSUE TITLE
Vim runs Sniffer running multiple times

### ISSUE THREAD

**Issue by andrewmichaelsmith** [jeffh/sniffer#25]
I'm using 0.3.5 and I find that when I save a single file my tests get run 2 or 3 times.

Any pointers for diagnosing this issue?

I'm using Ubuntu Linux, my sniffer instance is running inside a docker container, I'm editing the file (mounted locally on my host) with vim.

**Comment by andrewmichaelsmith** [comment]
One of our developers is using PyCharm (with the same docker setup) and when he saves the file it only runs the tests once. So it looks like this might be being caused by vim.

**Comment by jeffh** [comment]
Hey @andrewmichaelsmith,

Is your vim creating temporary files in the same directory? Sniffer might be picking those temporary files as changes to cause it to re-run the tests.

If you pass the `--debug` flag you can see which files cause sniffer to rerun the tests:

```bash
$ sniffer --debug
Did not find 'scent.py', running nose:
...
----------------------------------------------------------------------
Ran 3 tests in 0.009s

OK
In good standing
callback - changed  /Users/jeff/workspace/sniffer/sniffer/tests/test_api.py
```

**Comment by andrewmichaelsmith** [comment]
Hi @jeffh 

I have vim's swap files being created in /tmp/ so (assuming my understanding that sniffer is only looking in my cwd is correct) I think that rules those out.

Didn't realise there was a debug flag, I've experimented with that (grepping for "event" or "callback") and I get the following:

(All of this call backs come from me doing a single save of a single file in vim)

````
event: deleted /vol/app/tests/functional_tests.py
callback - deleted  /vol/app/tests/functional_tests.py
event: created /vol/app/tests/functional_tests.py
callback - created  /vol/app/tests/functional_tests.py
event: modified /vol/app/tests/functional_tests.py
callback - changed  /vol/app/tests/functional_tests.py
````

What's unusual is that when the tests run after this "deleted" event, it's still running the tests in functional_tests.py (I made one fail and it shows up for that run and all subsequent runs). Suggesting that file hasn't actually been deleted.

I'm a bit stumped to be honest!

**Comment by andrewmichaelsmith** [comment]
Not sure if this helps but I did a quick test using inotifywait, I had a file open in vim and saved it. These are the actions recorded (for a simple :w):

````
./ CREATE 4913
./ OPEN 4913
./ ATTRIB 4913
./ CLOSE_WRITE,CLOSE 4913
./ DELETE 4913
./ MOVED_FROM a.py
./ CREATE a.py
./ OPEN a.py
./ MODIFY a.py
./ CLOSE_WRITE,CLOSE a.py
./ ATTRIB a.py
````

**Comment by jeffh** [comment]
I think it might be a race condition. Sniffer tries to run per event, but FS events occur asynchronously, so by the time it runs the test, the files were already fully saved.

I don't have a linux box to test this on, but that's my basic understanding of the issue.

**Comment by andrewmichaelsmith** [comment]
I think this issue is because of vim's saving of files using swap files - it ends up saving, creating and moving a file on save.

I have (finally!) managed to work around this issue in vim using:

```set noswapfile```

In my vimrc
