### ISSUE TITLE
Sniffer in CI environment

### ISSUE THREAD

**Issue by HuffMoody** [jeffh/sniffer#33]
Hello,

Currently sniffer works great in development.  It finds all my tests and listens for events and reruns tests.  However, I am also trying to get this working in a CI environment where I don't want to block and listen for FS changes. I can't seem to find any documentation on how to setup sniffer this way.

If I were to implement this do you think you would merge?  Do you have any other recommendations for me to try instead?

Cheers.

**Comment by jeffh** [comment]
Hey Huff,
  

  
I'm not sure the context of what do you need this for? Normally a CI tool should automatically build / run tests after you push to repo.
  

  
If you could explain more the problem you're having, I'd like to understand that better.
  

  
- Jeff
  
  
  

  
>

**Comment by HuffMoody** [comment]
Hey Jeff,

I realize I should be using nosetests to run in the CI environment and sniffer for development.  Sorry, I come from a ruby background so I didn't realize the distinction between the two but it's basically just the equivalent to a rspec + guard setup.

Thanks for the reply.

**Comment by jeffh** [comment]
No problem! 😀 Closing
