### ISSUE TITLE
Sniffer runs twice after saving file in vim.

### ISSUE THREAD

**Issue by MrMino** [jeffh/sniffer#35]
Scenario: with vim, open a python file that contains test cases. Hit `:w`. Sniffer runs tests twice. 

This makes the output flash, which really gets on my nerves while jumping through the t/c/r cycle.

Is it problem with my `.vimrc` or is this a known bug? Is it possible that it is tripping up due to `.swp` files?

**Comment by jeffh** [comment]
Hey @MrMino,

It's a known issue. It's because vim is writing to the .swp file and then renames the file into its original filename. Sniffer causes this to detect two changes (one rename from the original, and another rename from the new file).

I'd love a pull request if you know a good way to resolve it 😄 

- Jeff

**Comment by MrMino** [comment]
@jeffh Wouldn't it be logical to implement a sanity delay when rerunning tests? I.e. an interval of time between two consecutive tests firings, in which file change events are ignored? Or a file ignoring settings, possibly based on `.gitignore`? 

Or even overhaul the file change detection part, so that it only detects a change inside a project when git says that a file changed?

Rationale: I won't be able to read the tests output in tenth of a second anyway, I probably wouldn't care about the files specified in `.gitignore`, and every change that git detects has a possibility of breaking the tests.

**Comment by jeffh** [comment]
Yeah, that all makes sense. If beer willing to merge a PR for that.

**Comment by BenDoan** [comment]
A simple vim-side fix for this is to change the backupcopy setting from auto/no to yes (run  `set backupcopy=yes` in .vimrc, details [here](http://vimdoc.sourceforge.net/htmldoc/options.html#'backupcopy')).

**Comment by MrMino** [comment]
Looks dead / won't fix. Closing.
