### ISSUE TITLE
./managa.py test class-one class-two with sniffer?

### ISSUE THREAD

**Issue by optikfluffel** [jeffh/sniffer#8]
Can I do something like `./managa.py test class-one class-two` with sniffer? otherwise it's testing all my installed django stuff what takes pretty long =/

**Comment by derek-adair** [comment]
I can verify @eddroid 's  solution as working, although i'd really expect this to be supported with sniffer sans scent.py.  Perhaps supporting django directly would be silly, I would just expect an easy way to run specific suites to be in this project.
